//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFRestCrud
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EXAMPLE
    {
        public int ID_EXAMPLE { get; set; }
        public string NM_EXAMPLE { get; set; }
        public Nullable<System.DateTime> DT_CREATE { get; set; }
    }
}
