//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFRestCrud
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestClusturedIndex
    {
        public int primcolumn { get; set; }
        public string firstname { get; set; }
    }
}
