//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFRestCrud
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTable
    {
        public int TestCol1 { get; set; }
        public string TestCol2 { get; set; }
        public string TestCol3 { get; set; }
        public int TestIntColumn { get; set; }
    }
}
